### ISSUE TITLE
Default Page is blank

### ISSUE THREAD

**Issue by GannonTank** [wangduanduan/v3-el-dashboard#1]
the app default page is blank, It is recommended to set up the home page routing. Thanks

**Comment by wangduanduan** [comment]
the v3-el-dashborad is just a demo, and very easy to learn。But no default page or default router。

if you want a default page or router, you can add it by yourself。i believe you can make it。

if you want a completed dashborad, maybe you should see https://github.com/PanJiaChen/vue-element-admin

**Comment by wangduanduan** [comment]
i add a default login page.
