### ISSUE TITLE
Default Page is blank too

### ISSUE THREAD

**Issue by Vivianluolita** [wangduanduan/v3-el-dashboard#2]

**Comment by wangduanduan** [comment]
the v3-el-dashborad is just a demo, and very easy to learn。But no default page or default router。

if you want a default page or router, you can add it by yourself。i believe you can make it。

if you want a completed dashborad, maybe you should see https://github.com/PanJiaChen/vue-element-admin

**Comment by Vivianluolita** [comment]
thanks,i will see your demo later, i havn`t completed my demo now,i will complete it soon.

**Comment by Vivianluolita** [comment]
> the v3-el-dashborad is just a demo, and very easy to learn。But no default page or default router。
> 
> if you want a default page or router, you can add it by yourself。i believe you can make it。
> 
> if you want a completed dashborad, maybe you should see https://github.com/PanJiaChen/vue-element-admin

thanks,i will see your demo later, i havn`t completed my demo now,i will complete it soon.
